# disable status bar
set -g status off

# pane border
set -g pane-border-style bg=default,fg=blue

# active pane border
set -g pane-active-border-style bg=default,fg=white

# status style
set -g status-style bg=white,fg=black,bold

# command bar style
set -g message-style bg=white,fg=black
set -g message-command-style bg=black,fg=white

# session selection window style
set -wg mode-style bg=white,fg=black

# rebind prefix from <C-b> to <C-space>
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# make double escape work
set -sg escape-time 10

# vim-like window navigation bindings
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# open new pane in the current dir
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# mouse support
set -g mouse on

# clipboard
bind-key -T edit-mode-vi Up send-keys -X history-up
bind-key -T edit-mode-vi Down send-keys -X history-down
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"
unbind-key -T copy-mode-vi Space     ;   bind-key -T copy-mode-vi v send-keys -X begin-selection
unbind-key -T copy-mode-vi Enter     ;   bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
unbind-key -T copy-mode-vi C-v       ;   bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
unbind-key -T copy-mode-vi [         ;   bind-key -T copy-mode-vi [ send-keys -X begin-selection
unbind-key -T copy-mode-vi ]         ;   bind-key -T copy-mode-vi ] send-keys -X copy-selection
