# disable status bar
set -g status off

# pane border
set -g pane-border-style bg=default,fg=blue

# active pane border
set -g pane-active-border-style bg=default,fg=white

# status style
set -g status-style bg=white,fg=black,bold

# command bar style
set -g message-style bg=white,fg=black
set -g message-command-style bg=black,fg=white

# session selection window style
set -wg mode-style bg=white,fg=black

# rebind prefix from <C-b> to <C-space>
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# make double escape work
set -sg escape-time 10

# vim-like window navigation bindings
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# open new pane in the current dir
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# mouse support
set -g mouse on

# clipboard
bind -T edit-mode-vi Up send-keys -X history-up
bind -T edit-mode-vi Down send-keys -X history-down
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"
unbind -T copy-mode-vi Space ; bind -T copy-mode-vi v send -X begin-selection
unbind -T copy-mode-vi Enter ; bind -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy"
unbind -T copy-mode-vi C-v ; bind -T copy-mode-vi C-v send -X rectangle-toggle
unbind -T copy-mode-vi [ ; bind -T copy-mode-vi [ send -X begin-selection
unbind -T copy-mode-vi ] ; bind -T copy-mode-vi ] send -X copy-selection
